ld \
-demangle \
-lto_library \
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib \
-dynamic \
-arch \
x86_64 \
-platform_version \
macos \
12.3.0 \
12.3 \
-syslibroot \
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk \
-o \
/Users/bytedance/Library/Developer/Xcode/DerivedData/hash-aemzjpwsctkicsbrxrmwmxwtkcqs/Build/Products/Debug/hash \
-L/Users/bytedance/Library/Developer/Xcode/DerivedData/hash-aemzjpwsctkicsbrxrmwmxwtkcqs/Build/Products/Debug \
-L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx \
-L/usr/lib/swift \
-rpath \
/usr/lib/swift \
-object_path_lto \
/Users/bytedance/Library/Developer/Xcode/DerivedData/hash-aemzjpwsctkicsbrxrmwmxwtkcqs/Build/Intermediates.noindex/hash.build/Debug/hash.build/Objects-normal/x86_64/hash_lto.o \
-export_dynamic \
-no_deduplicate \
-add_ast_path \
/Users/bytedance/Library/Developer/Xcode/DerivedData/hash-aemzjpwsctkicsbrxrmwmxwtkcqs/Build/Intermediates.noindex/hash.build/Debug/hash.build/Objects-normal/x86_64/hash.swiftmodule \
-all_load \
-framework \
FrameworkB \
-framework \
FrameworkA \
-filelist \
/Users/bytedance/Library/Developer/Xcode/DerivedData/hash-aemzjpwsctkicsbrxrmwmxwtkcqs/Build/Intermediates.noindex/hash.build/Debug/hash.build/Objects-normal/x86_64/hash.LinkFileList \
-no_adhoc_codesign \
-dependency_info \
/Users/bytedance/Library/Developer/Xcode/DerivedData/hash-aemzjpwsctkicsbrxrmwmxwtkcqs/Build/Intermediates.noindex/hash.build/Debug/hash.build/Objects-normal/x86_64/hash_dependency_info.dat \
-framework \
Foundation \
-lobjc \
-lSystem \
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/lib/darwin/libclang_rt.osx.a \
-F/Users/bytedance/Library/Developer/Xcode/DerivedData/hash-aemzjpwsctkicsbrxrmwmxwtkcqs/Build/Products/Debug \
-F/Users/bytedance/Xcode/hash/hash